name: onesignal_flutter
description: OneSignal is a free push notification service for mobile apps. This plugin makes it easy to integrate your flutter app with OneSignal
version: 5.4.2
homepage: https://github.com/OneSignal/OneSignal-Flutter-SDK

# Uses rps package for scripts
# E.g.`rps test` to run tests
scripts:
  test: flutter test --coverage && dart run dlcov -c 95 --log=0 --include-untested-files=true
  format-check: dart format --set-exit-if-changed --output=none . && android/gradlew spotlessCheck
  format: dart format . && android/gradlew spotlessApply

flutter:
  plugin:
    platforms:
      android:
        package: com.onesignal.flutter
        pluginClass: OneSignalPlugin
      ios:
        pluginClass: OneSignalPlugin

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.5.1
  flutter_test:
    sdk: flutter
  dlcov: ^4.2.1
  rps: ^0.9.1

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.0.0"
