name: demo
description: OneSignal Flutter SDK Demo App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  onesignal_flutter:
    path: ../../
  provider: ^6.1.0
  shared_preferences: ^2.3.0
  http: ^1.2.0
  url_launcher: ^6.2.0
  flutter_svg: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/onesignal_logo.svg
